<a href="https://colab.research.google.com/github/nizardbsk/pl_pytorch_tutorial/blob/main/11_entropy_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import torch.nn as nn
import numpy as np

In [2]:
loss = nn.CrossEntropyLoss()

# 1 sample
Y = torch.tensor([0])
# n_samples * n_classes = 1*3
Y_pred_good = torch.tensor([[2.0,1.0,0.1]])
Y_pred_bad = torch.tensor([[0.5,2.0,0.3]])

l1 = loss(Y_pred_good,Y)
l2 = loss(Y_pred_bad,Y)
print(l1.item())
print(l2.item())

0.4170299470424652
1.840616226196289


In [3]:
_,predictions1 = torch.max(Y_pred_good,1)
_,predictions2 = torch.max(Y_pred_bad,1)
print(predictions1)
print(predictions2)

tensor([0])
tensor([1])


In [5]:
# 3 sample
Y = torch.tensor([2,0,1])
# n_samples * n_classes = 3*3
Y_pred_good3 = torch.tensor([[0.1,1.0,2.1],[2.0,1.0,0.1],[0.1,3.0,0.1]])
Y_pred_bad3 = torch.tensor([[2.1,1.0,0.1],[0.1,1.0,2.1],[0.1,3.0,0.1]])

l3 = loss(Y_pred_good3,Y)
l4 = loss(Y_pred_bad3,Y)
print(l3.item())
print(l4.item())
_,predictions3 = torch.max(Y_pred_good3,1)
_,predictions4 = torch.max(Y_pred_bad3,1)
print(predictions3)
print(predictions4)

0.3018244206905365
1.6241613626480103
tensor([2, 0, 1])
tensor([0, 2, 1])
