<a href="https://colab.research.google.com/github/nizardbsk/pl_pytorch_tutorial/blob/main/1_tensor_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
2+2


4

In [3]:
import torch

In [8]:
x = torch.empty(4)
print(x)
x[1]

tensor([1.2162e-19, 4.5321e-41, 1.3806e-19, 4.5321e-41])


tensor(4.5321e-41)

In [9]:
y = torch.rand(4,7)
y

tensor([[0.6270, 0.5088, 0.2805, 0.5874, 0.5164, 0.2814, 0.9221],
        [0.9852, 0.0020, 0.8127, 0.8997, 0.4446, 0.1554, 0.5855],
        [0.8622, 0.5852, 0.7698, 0.3085, 0.3875, 0.1247, 0.6429],
        [0.8706, 0.3325, 0.0559, 0.8853, 0.8888, 0.7528, 0.9639]])

basic tensor operations

In [11]:
x = torch.rand(2,2)
y = torch.rand(2,2)
print('x :',x)
print('y :',y)
z = x+y
# or z = torch.add(x,y)
print('z :',z)

x : tensor([[0.9492, 0.5825],
        [0.0984, 0.7020]])
y : tensor([[0.6474, 0.3904],
        [0.8797, 0.0437]])
z : tensor([[1.5966, 0.9730],
        [0.9781, 0.7456]])


In [12]:
# inpalce addition
y.add_(x)


tensor([[1.5966, 0.9730],
        [0.9781, 0.7456]])

In [13]:
# division
w = torch.div(x,y)
w

tensor([[0.5945, 0.5987],
        [0.1006, 0.9414]])

In [15]:
v = torch.rand(5,3)
print(v)
# print the first column of all the rows
print(v[:,0])
# row number 1 and all columns
print(v[1,:])

tensor([[0.0457, 0.5078, 0.0782],
        [0.0894, 0.7223, 0.8220],
        [0.9118, 0.8967, 0.9157],
        [0.6809, 0.1939, 0.4559],
        [0.1660, 0.3095, 0.3596]])
tensor([0.0457, 0.0894, 0.9118, 0.6809, 0.1660])
tensor([0.0894, 0.7223, 0.8220])


Reshaping a tensor :

In [19]:
f = torch.rand(4,4)
print(f)
g = f.view(2,8)
print(g)

tensor([[0.3897, 0.9109, 0.0047, 0.6162],
        [0.0677, 0.1856, 0.9010, 0.2336],
        [0.2547, 0.2396, 0.8232, 0.7111],
        [0.7232, 0.1320, 0.2743, 0.6157]])
tensor([[0.3897, 0.9109, 0.0047, 0.6162, 0.0677, 0.1856, 0.9010, 0.2336],
        [0.2547, 0.2396, 0.8232, 0.7111, 0.7232, 0.1320, 0.2743, 0.6157]])


In [22]:
# convert from numpy to tensor and oposite
import numpy as np
a = torch.ones(5)
print(a)
b = a.numpy()
print(b)
print(type(b))



tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>


In [23]:
# from numpy to torch tensor

c = np.ones(5)
print(c)
d = torch.from_numpy(c)
print(d)


[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
