<a href="https://colab.research.google.com/github/nizardbsk/pl_pytorch_tutorial/blob/main/2_gradient_calc_Autograd.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
x = torch.randn(3,requires_grad=True)
print(x)

tensor([ 1.5880,  0.7394, -0.8435], requires_grad=True)


requires grad = True,allows us to calculate the gradient in respzct to x in the future

In [6]:
y = x+2
print(y)
z= y*y*2
z=z.mean()
print(z)

tensor([3.5880, 2.7394, 1.1565], grad_fn=<AddBackward0>)
tensor(14.4766, grad_fn=<MeanBackward0>)


In [7]:
# calculating the gradient of z with resspect to x dz/dx
# if requires_grad in x was 'False',this won't be possible
z.backward()# dz/dx
print(x.grad)

tensor([4.7839, 3.6525, 1.5419])


In [10]:
# simple training example
weights  =torch.ones(4,requires_grad=True)
for epoch in range(2):
  model_outputs = (weights*3).sum()
  model_outputs.backward()
  print(weights.grad)
  weights.grad.zero_()

tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
