<a href="https://colab.research.google.com/github/nizardbsk/pl_pytorch_tutorial/blob/main/Dataset_Dataloader_Test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import torchvision
from torch.utils.data import Dataset,DataLoader
import numpy as np
import math


In [2]:
class WineDataset(Dataset):
  def __init__(self):
    # data loading
    xy = np.loadtxt('wine.csv',delimiter=',',dtype=np.float32,skiprows=1)
    self.x = torch.from_numpy(xy[:, 1:])
    self.y = torch.from_numpy(xy[:, [0]])
    self.n_samples = xy.shape[0]

  def __getitem__(self,index):
    # dataset[0]
    return self.x[index], self.y[index]

  def __len__(self):
    # len(dataset)
    return self.n_samples

In [3]:
from google.colab import files
uploaded = files.upload()

Saving wine.csv to wine.csv


In [4]:
dataset = WineDataset()
first_data = dataset[0]
features,labels = first_data
print(features,labels)

tensor([1.4230e+01, 1.7100e+00, 2.4300e+00, 1.5600e+01, 1.2700e+02, 2.8000e+00,
        3.0600e+00, 2.8000e-01, 2.2900e+00, 5.6400e+00, 1.0400e+00, 3.9200e+00,
        1.0650e+03]) tensor([1.])


In [5]:
dataloader = DataLoader(dataset=dataset, batch_size=4, shuffle=True,num_workers=2)

dataiter = iter(dataloader)
data = next(dataiter)
features,labels = data
print(features,labels)

tensor([[1.2850e+01, 1.6000e+00, 2.5200e+00, 1.7800e+01, 9.5000e+01, 2.4800e+00,
         2.3700e+00, 2.6000e-01, 1.4600e+00, 3.9300e+00, 1.0900e+00, 3.6300e+00,
         1.0150e+03],
        [1.3030e+01, 9.0000e-01, 1.7100e+00, 1.6000e+01, 8.6000e+01, 1.9500e+00,
         2.0300e+00, 2.4000e-01, 1.4600e+00, 4.6000e+00, 1.1900e+00, 2.4800e+00,
         3.9200e+02],
        [1.1760e+01, 2.6800e+00, 2.9200e+00, 2.0000e+01, 1.0300e+02, 1.7500e+00,
         2.0300e+00, 6.0000e-01, 1.0500e+00, 3.8000e+00, 1.2300e+00, 2.5000e+00,
         6.0700e+02],
        [1.3830e+01, 1.6500e+00, 2.6000e+00, 1.7200e+01, 9.4000e+01, 2.4500e+00,
         2.9900e+00, 2.2000e-01, 2.2900e+00, 5.6000e+00, 1.2400e+00, 3.3700e+00,
         1.2650e+03]]) tensor([[1.],
        [2.],
        [2.],
        [1.]])


In [7]:
dataloader2 = DataLoader(dataset=dataset, batch_size=7, shuffle=True,num_workers=2)

dataiter2 = iter(dataloader2)
data2 = next(dataiter2)
features2,labels2 = data2
print(features2,labels2)

tensor([[1.2850e+01, 1.6000e+00, 2.5200e+00, 1.7800e+01, 9.5000e+01, 2.4800e+00,
         2.3700e+00, 2.6000e-01, 1.4600e+00, 3.9300e+00, 1.0900e+00, 3.6300e+00,
         1.0150e+03],
        [1.3160e+01, 2.3600e+00, 2.6700e+00, 1.8600e+01, 1.0100e+02, 2.8000e+00,
         3.2400e+00, 3.0000e-01, 2.8100e+00, 5.6800e+00, 1.0300e+00, 3.1700e+00,
         1.1850e+03],
        [1.2720e+01, 1.8100e+00, 2.2000e+00, 1.8800e+01, 8.6000e+01, 2.2000e+00,
         2.5300e+00, 2.6000e-01, 1.7700e+00, 3.9000e+00, 1.1600e+00, 3.1400e+00,
         7.1400e+02],
        [1.3300e+01, 1.7200e+00, 2.1400e+00, 1.7000e+01, 9.4000e+01, 2.4000e+00,
         2.1900e+00, 2.7000e-01, 1.3500e+00, 3.9500e+00, 1.0200e+00, 2.7700e+00,
         1.2850e+03],
        [1.2170e+01, 1.4500e+00, 2.5300e+00, 1.9000e+01, 1.0400e+02, 1.8900e+00,
         1.7500e+00, 4.5000e-01, 1.0300e+00, 2.9500e+00, 1.4500e+00, 2.2300e+00,
         3.5500e+02],
        [1.3170e+01, 2.5900e+00, 2.3700e+00, 2.0000e+01, 1.2000e+02, 1.6500e+00,

In [18]:
print(dataset[177])
print(len(dataloader))
print(len(dataloader2))

(tensor([ 14.1300,   4.1000,   2.7400,  24.5000,  96.0000,   2.0500,   0.7600,
          0.5600,   1.3500,   9.2000,   0.6100,   1.6000, 560.0000]), tensor([3.]))
45
26


In [19]:
# Training loop
n_epochs = 2
total_samples = len(dataset)
n_iters = math.ceil(total_samples/4)
print(total_samples,n_iters)

178 45


number of iterations is the lenght of dataloader,and it is repeated in the n_epochs,so the full iterations is : n_epochs * n_iters

In [29]:
for epoch in range(n_epochs):
  for i,(inputs,labels) in enumerate(dataloader):
    if (i%5)==0:
      print(f'epoch : {epoch+1}/{n_epochs}, iter : {i+1}:{n_iters}, inputs {inputs.shape}')
    if i==22:
      print(inputs)

epoch : 1/2, iter : 1:45, inputs torch.Size([4, 13])
epoch : 1/2, iter : 6:45, inputs torch.Size([4, 13])
epoch : 1/2, iter : 11:45, inputs torch.Size([4, 13])
epoch : 1/2, iter : 16:45, inputs torch.Size([4, 13])
epoch : 1/2, iter : 21:45, inputs torch.Size([4, 13])
tensor([[1.3710e+01, 1.8600e+00, 2.3600e+00, 1.6600e+01, 1.0100e+02, 2.6100e+00,
         2.8800e+00, 2.7000e-01, 1.6900e+00, 3.8000e+00, 1.1100e+00, 4.0000e+00,
         1.0350e+03],
        [1.3770e+01, 1.9000e+00, 2.6800e+00, 1.7100e+01, 1.1500e+02, 3.0000e+00,
         2.7900e+00, 3.9000e-01, 1.6800e+00, 6.3000e+00, 1.1300e+00, 2.9300e+00,
         1.3750e+03],
        [1.1820e+01, 1.7200e+00, 1.8800e+00, 1.9500e+01, 8.6000e+01, 2.5000e+00,
         1.6400e+00, 3.7000e-01, 1.4200e+00, 2.0600e+00, 9.4000e-01, 2.4400e+00,
         4.1500e+02],
        [1.2850e+01, 1.6000e+00, 2.5200e+00, 1.7800e+01, 9.5000e+01, 2.4800e+00,
         2.3700e+00, 2.6000e-01, 1.4600e+00, 3.9300e+00, 1.0900e+00, 3.6300e+00,
         1.0150e+0

In [28]:
for epoch in range(n_epochs):
  for i,(inputs2,labels2) in enumerate(dataloader2):
    if (i%5)==0:
      print(f'epoch : {epoch+1}/{n_epochs}, iter : {i+1}/{math.ceil(len(dataset)/7)}, inputs {inputs2.shape}')
    if i==22:
      print(inputs2)

epoch : 1/2, iter : 1/26, inputs torch.Size([7, 13])
epoch : 1/2, iter : 6/26, inputs torch.Size([7, 13])
epoch : 1/2, iter : 11/26, inputs torch.Size([7, 13])
epoch : 1/2, iter : 16/26, inputs torch.Size([7, 13])
epoch : 1/2, iter : 21/26, inputs torch.Size([7, 13])
tensor([[1.3580e+01, 2.5800e+00, 2.6900e+00, 2.4500e+01, 1.0500e+02, 1.5500e+00,
         8.4000e-01, 3.9000e-01, 1.5400e+00, 8.6600e+00, 7.4000e-01, 1.8000e+00,
         7.5000e+02],
        [1.3030e+01, 9.0000e-01, 1.7100e+00, 1.6000e+01, 8.6000e+01, 1.9500e+00,
         2.0300e+00, 2.4000e-01, 1.4600e+00, 4.6000e+00, 1.1900e+00, 2.4800e+00,
         3.9200e+02],
        [1.3160e+01, 2.3600e+00, 2.6700e+00, 1.8600e+01, 1.0100e+02, 2.8000e+00,
         3.2400e+00, 3.0000e-01, 2.8100e+00, 5.6800e+00, 1.0300e+00, 3.1700e+00,
         1.1850e+03],
        [1.2290e+01, 3.1700e+00, 2.2100e+00, 1.8000e+01, 8.8000e+01, 2.8500e+00,
         2.9900e+00, 4.5000e-01, 2.8100e+00, 2.3000e+00, 1.4200e+00, 2.8300e+00,
         4.0600e+0