<a href="https://colab.research.google.com/github/nizardbsk/pl_pytorch_tutorial/blob/main/Feed_Forward_test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# MNIST
# DataLoader , Transformation
# Multi layer NN , Act function
# Loss and Optimizer
# Training Loop (batch training)
# Model evaluation
# GPU support

In [2]:
import torch
import torch.nn as nn
import torchvision
import torchvision.transforms as transforms
import matplotlib.pyplot as plt

In [16]:
input_size = 784 #28x28
hidden_size = 100
num_classes = 10
num_epochs = 2
batch_size = 100
lr = 0.003

# MNIST
train_dataset = torchvision.datasets.MNIST(root='./data',train=True,transform=transforms.ToTensor(),download=True)
test_dataset = torchvision.datasets.MNIST(root='./data',train=False,transform=transforms.ToTensor())

train_loader = torch.utils.data.DataLoader(dataset=train_dataset,batch_size=batch_size,shuffle=True)
test_loader = torch.utils.data.DataLoader(dataset=test_dataset,batch_size=batch_size,shuffle=False)
print(f'len train : {len(train_loader)}, len test : {len(test_loader)}')

len train : 600, len test : 100


In [5]:
print(f'len train dataset : {len(train_dataset)}, len test : {len(test_dataset)}')

len train dataset : 60000, len test : 10000


In [6]:
examples = iter(train_loader)
samples,labels = next(examples)
print(samples)

tensor([[[[0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          ...,
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.]]],


        [[[0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          ...,
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.]]],


        [[[0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          ...,
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.]]],


        ...,


        [[[0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          ...,
          [0., 0., 0.,  ..., 0.

In [18]:
print(samples.reshape(-1,28*28))

tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])


In [19]:
print(samples.reshape(-1,28*28).shape)

torch.Size([100, 784])


In [20]:
print(samples[0].reshape(-1,28*28))

tensor([[0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.1608, 0.6157,
         0.4471, 0.0510, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0510,
         0.9176, 0.9961, 0.2510, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0824, 0.9451, 0.8627, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0

In [7]:
print(labels)

tensor([2, 8, 9, 8, 5, 6, 7, 3, 2, 1, 3, 8, 7, 2, 4, 1, 9, 7, 7, 6, 8, 6, 2, 0,
        9, 6, 9, 1, 0, 9, 5, 0, 6, 2, 3, 2, 1, 2, 1, 3, 0, 9, 8, 1, 3, 0, 9, 9,
        9, 3, 1, 6, 1, 6, 4, 8, 3, 4, 5, 5, 1, 7, 8, 5, 9, 4, 4, 0, 3, 6, 3, 0,
        8, 1, 8, 2, 8, 7, 0, 6, 0, 5, 6, 2, 6, 5, 0, 1, 6, 1, 2, 8, 7, 8, 7, 9,
        7, 7, 1, 2])


In [23]:
print(labels.shape[0])

100


In [8]:
print(f'samples shape : {samples.shape}, labels shape {labels.shape}')

samples shape : torch.Size([100, 1, 28, 28]), labels shape torch.Size([100])


In [9]:
print(samples[1][0])

tensor([[0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000

In [10]:
print(samples[1][0].shape)

torch.Size([28, 28])


In [11]:
print(samples[1].shape)

torch.Size([1, 28, 28])


In [12]:
print(samples[1][0][5])

tensor([0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0627, 0.2078, 0.5608, 0.5608, 0.8078, 0.9922, 0.9922,
        0.9922, 0.9922, 0.6549, 0.1059, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000])


In [13]:
print(samples[1][0][5].shape)

torch.Size([28])


In [14]:
class NeuralNetwork(nn.Module):
  def __init__(self,input_size,hidden_size,num_classes):
    super(NeuralNetwork,self).__init__()
    self.linear1 = nn.Linear(input_size,hidden_size)
    self.relu = nn.ReLU()
    self.linear2 = nn.Linear(hidden_size,num_classes)
  def forward(self,x):
    x = self.linear1(x)
    x = self.relu(x)
    x = self.linear2(x)
    return x

In [15]:
model = NeuralNetwork(input_size,hidden_size,num_classes)

In [17]:
# loss & optimizer
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(),lr=lr)

In [21]:
# train loop
n_total_steps = len(train_loader)
for epoch in range(num_epochs):
  for i,(images,labels) in enumerate(train_loader):
    images = images.reshape(-1,28*28)

    # forward
    outputs = model(images)
    loss = criterion(outputs,labels)
    #backward
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    if (i+1)%100 == 0:
      print(f'epoch : {epoch+1}/{num_epochs}, step : {i+1}/{n_total_steps},loss = {loss.item():.4f}')

epoch : 1/2, step : 100/600,loss = 0.4009
epoch : 1/2, step : 200/600,loss = 0.3327
epoch : 1/2, step : 300/600,loss = 0.4227
epoch : 1/2, step : 400/600,loss = 0.2001
epoch : 1/2, step : 500/600,loss = 0.1113
epoch : 1/2, step : 600/600,loss = 0.1015
epoch : 2/2, step : 100/600,loss = 0.0958
epoch : 2/2, step : 200/600,loss = 0.1890
epoch : 2/2, step : 300/600,loss = 0.1378
epoch : 2/2, step : 400/600,loss = 0.1117
epoch : 2/2, step : 500/600,loss = 0.1364
epoch : 2/2, step : 600/600,loss = 0.1088


In [24]:
# test
with torch.no_grad():
  n_correct = 0
  n_samples = 0
  for images,labels in test_loader :
    images = images.reshape(-1,28*28)
    outputs = model(images)

    #value,index
    _,predictions = torch.max(outputs,1)
    n_samples += labels.shape[0]
    n_correct = (predictions==labels).sum().item()
  acc = 100.0 * n_correct/n_samples
  print(f'accuracy : {acc}')

accuracy : 0.96
